// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/cloud/gcp/resource/folder/state/model.proto

package com.leftbin.commons.proto.v1.cloud.gcp.resource.folder.state;

public final class ModelProto {
  private ModelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_leftbin_commons_proto_v1_cloud_gcp_resource_folder_state_GcpFolderState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_leftbin_commons_proto_v1_cloud_gcp_resource_folder_state_GcpFolderState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nDleftbin/commons/proto/v1/cloud/gcp/res" +
      "ource/folder/state/model.proto\0228leftbin." +
      "commons.proto.v1.cloud.gcp.resource.fold" +
      "er.state\"[\n\016GcpFolderState\022\016\n\002id\030\001 \001(\tR\002" +
      "id\022!\n\014display_name\030\002 \001(\tR\013displayName\022\026\n" +
      "\006parent\030\003 \001(\tR\006parentB\275\003\n<com.leftbin.co" +
      "mmons.proto.v1.cloud.gcp.resource.folder" +
      ".stateB\nModelProtoP\001Zcgithub.com/planton" +
      "cloud/proto-commons/zzgo/leftbin/commons" +
      "/proto/v1/cloud/gcp/resource/folder/stat" +
      "e\242\002\tLCPVCGRFS\252\0028Leftbin.Commons.Proto.V1" +
      ".Cloud.Gcp.Resource.Folder.State\312\0028Leftb" +
      "in\\Commons\\Proto\\V1\\Cloud\\Gcp\\Resource\\F" +
      "older\\State\342\002DLeftbin\\Commons\\Proto\\V1\\C" +
      "loud\\Gcp\\Resource\\Folder\\State\\GPBMetada" +
      "ta\352\002@Leftbin::Commons::Proto::V1::Cloud:" +
      ":Gcp::Resource::Folder::Stateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_leftbin_commons_proto_v1_cloud_gcp_resource_folder_state_GcpFolderState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_leftbin_commons_proto_v1_cloud_gcp_resource_folder_state_GcpFolderState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_leftbin_commons_proto_v1_cloud_gcp_resource_folder_state_GcpFolderState_descriptor,
        new java.lang.String[] { "Id", "DisplayName", "Parent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
