// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/english/rpc/enums/enums.proto

package com.leftbin.commons.proto.v1.english.rpc.enums;

public final class EnumsProto {
  private EnumsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_leftbin_commons_proto_v1_english_rpc_enums_Word_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_leftbin_commons_proto_v1_english_rpc_enums_Word_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_leftbin_commons_proto_v1_english_rpc_enums_Acronym_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_leftbin_commons_proto_v1_english_rpc_enums_Acronym_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6leftbin/commons/proto/v1/english/rpc/e" +
      "nums/enums.proto\022*leftbin.commons.proto." +
      "v1.english.rpc.enums\"\260\006\n\004Word\"\247\006\n\010WordEn" +
      "um\022\024\n\020word_unspecified\020\000\022\007\n\003app\020\001\022\017\n\013app" +
      "lication\020\002\022\007\n\003aws\020\003\022\t\n\005azure\020\004\022\010\n\004bill\020\005" +
      "\022\013\n\007company\020\006\022\n\n\006config\020\007\022\007\n\003cpu\020\010\022\t\n\005de" +
      "bug\020\t\022\n\n\006docker\020\n\022\n\n\006domain\020\013\022\t\n\005email\020\014" +
      "\022\014\n\010endpoint\020\r\022\014\n\010external\020\016\022\010\n\004file\020\017\022\007" +
      "\n\003gcp\020\020\022\n\n\006google\020\021\022\013\n\007hosting\020\022\022\014\n\010host" +
      "name\020\023\022\006\n\002id\020\024\022\013\n\007ingress\020\025\022\r\n\tinstances" +
      "\020\026\022\014\n\010internal\020\027\022\006\n\002ip\020\030\022\007\n\003key\020\031\022\016\n\nkub" +
      "econfig\020\032\022\016\n\nkubernetes\020\033\022\r\n\tlocalhost\020\034" +
      "\022\013\n\007machine\020\035\022\010\n\004main\020\036\022\t\n\005maven\020\037\022\n\n\006me" +
      "mory\020 \022\020\n\014microservice\020!\022\010\n\004name\020\"\022\017\n\013na" +
      "meservers\020#\022\r\n\tnamespace\020$\022\013\n\007network\020%\022" +
      "\007\n\003npm\020&\022\n\n\006number\020\'\022\007\n\003org\020(\022\n\n\006parent\020" +
      ")\022\014\n\010postgres\020*\022\013\n\007product\020+\022\013\n\007project\020" +
      ",\022\n\n\006python\020-\022\010\n\004repo\020.\022\n\n\006review\020/\022\n\n\006s" +
      "erver\0200\022\013\n\007servers\0201\022\t\n\005share\0202\022\023\n\017share" +
      "d_services\0203\022\t\n\005spilo\0204\022\010\n\004spot\0205\022\013\n\007stu" +
      "nnel\0206\022\010\n\004team\0207\022\010\n\004type\0208\022\014\n\010username\0209" +
      "\022\010\n\004util\020:\022\013\n\007version\020;\022\014\n\010workload\020<\022\007\n" +
      "\003url\020=\022\007\n\003env\020>\022\t\n\005kafka\020?\022\013\n\007unknown\020@\"" +
      "B\n\007Acronym\"7\n\013AcronymEnum\022\027\n\023ACRONYM_UNS" +
      "PECIFIED\020\000\022\006\n\002NW\020\001\022\007\n\003RPC\020\002B\345\002\n.com.left" +
      "bin.commons.proto.v1.english.rpc.enumsB\n" +
      "EnumsProtoP\001ZUgithub.com/plantoncloud/pr" +
      "oto-commons/zzgo/leftbin/commons/proto/v" +
      "1/english/rpc/enums\242\002\007LCPVERE\252\002*Leftbin." +
      "Commons.Proto.V1.English.Rpc.Enums\312\002*Lef" +
      "tbin\\Commons\\Proto\\V1\\English\\Rpc\\Enums\342" +
      "\0026Leftbin\\Commons\\Proto\\V1\\English\\Rpc\\E" +
      "nums\\GPBMetadata\352\0020Leftbin::Commons::Pro" +
      "to::V1::English::Rpc::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_leftbin_commons_proto_v1_english_rpc_enums_Word_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_leftbin_commons_proto_v1_english_rpc_enums_Word_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_leftbin_commons_proto_v1_english_rpc_enums_Word_descriptor,
        new java.lang.String[] { });
    internal_static_leftbin_commons_proto_v1_english_rpc_enums_Acronym_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_leftbin_commons_proto_v1_english_rpc_enums_Acronym_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_leftbin_commons_proto_v1_english_rpc_enums_Acronym_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
