// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/english/rpc/enums/enums.proto

package com.leftbin.commons.proto.v1.english.rpc.enums;

public interface WordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.english.rpc.enums.Word)
    com.google.protobuf.MessageOrBuilder {
}
