// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/rpc/pagination/google/model.proto

package com.leftbin.commons.proto.v1.rpc.pagination.google;

public interface GooglePageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.rpc.pagination.google.GooglePageInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *google apis include a token to retrieve next page of results.
   *if there are no more items to return, the next_page_token is empty
   * </pre>
   *
   * <code>string page_token = 1 [json_name = "pageToken"];</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <pre>
   *google apis include a token to retrieve next page of results.
   *if there are no more items to return, the next_page_token is empty
   * </pre>
   *
   * <code>string page_token = 1 [json_name = "pageToken"];</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();

  /**
   * <pre>
   *number of items to include in the result
   * </pre>
   *
   * <code>int32 size = 2 [json_name = "size"];</code>
   * @return The size.
   */
  int getSize();
}
