// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/cloud/gcp/resource/project/rpc/model.proto

package com.leftbin.commons.proto.v1.cloud.gcp.resource.project.rpc;

public interface GcpProjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.cloud.gcp.resource.project.rpc.GcpProject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of the gcp project
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * name of the gcp project
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * id of the gcp project
   * </pre>
   *
   * <code>string id = 2 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * id of the gcp project
   * </pre>
   *
   * <code>string id = 2 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * number of the gcp project
   * </pre>
   *
   * <code>string number = 3 [json_name = "number"];</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <pre>
   * number of the gcp project
   * </pre>
   *
   * <code>string number = 3 [json_name = "number"];</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <pre>
   * id of the billing account
   * </pre>
   *
   * <code>string billing_account_id = 4 [json_name = "billingAccountId"];</code>
   * @return The billingAccountId.
   */
  java.lang.String getBillingAccountId();
  /**
   * <pre>
   * id of the billing account
   * </pre>
   *
   * <code>string billing_account_id = 4 [json_name = "billingAccountId"];</code>
   * @return The bytes for billingAccountId.
   */
  com.google.protobuf.ByteString
      getBillingAccountIdBytes();
}
