// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/timeline/rpc/model.proto

package com.leftbin.commons.proto.v1.timeline.rpc;

public interface ActivityUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of the field in resource that got updated
   * </pre>
   *
   * <code>string field_name = 1 [json_name = "fieldName"];</code>
   * @return The fieldName.
   */
  java.lang.String getFieldName();
  /**
   * <pre>
   * name of the field in resource that got updated
   * </pre>
   *
   * <code>string field_name = 1 [json_name = "fieldName"];</code>
   * @return The bytes for fieldName.
   */
  com.google.protobuf.ByteString
      getFieldNameBytes();

  /**
   * <pre>
   * data type of the field
   * </pre>
   *
   * <code>string field_type = 2 [json_name = "fieldType"];</code>
   * @return The fieldType.
   */
  java.lang.String getFieldType();
  /**
   * <pre>
   * data type of the field
   * </pre>
   *
   * <code>string field_type = 2 [json_name = "fieldType"];</code>
   * @return The bytes for fieldType.
   */
  com.google.protobuf.ByteString
      getFieldTypeBytes();

  /**
   * <pre>
   * old value of the field
   * will be blank in case of filed type list
   * </pre>
   *
   * <code>string old_value = 3 [json_name = "oldValue"];</code>
   * @return The oldValue.
   */
  java.lang.String getOldValue();
  /**
   * <pre>
   * old value of the field
   * will be blank in case of filed type list
   * </pre>
   *
   * <code>string old_value = 3 [json_name = "oldValue"];</code>
   * @return The bytes for oldValue.
   */
  com.google.protobuf.ByteString
      getOldValueBytes();

  /**
   * <pre>
   * new value of the field
   * will be blank in case of filed type list
   * </pre>
   *
   * <code>string new_value = 4 [json_name = "newValue"];</code>
   * @return The newValue.
   */
  java.lang.String getNewValue();
  /**
   * <pre>
   * new value of the field
   * will be blank in case of filed type list
   * </pre>
   *
   * <code>string new_value = 4 [json_name = "newValue"];</code>
   * @return The bytes for newValue.
   */
  com.google.protobuf.ByteString
      getNewValueBytes();

  /**
   * <pre>
   * this is specific to field data type list
   * will have the new values added to the list
   * </pre>
   *
   * <code>repeated string added_values = 5 [json_name = "addedValues"];</code>
   * @return A list containing the addedValues.
   */
  java.util.List<java.lang.String>
      getAddedValuesList();
  /**
   * <pre>
   * this is specific to field data type list
   * will have the new values added to the list
   * </pre>
   *
   * <code>repeated string added_values = 5 [json_name = "addedValues"];</code>
   * @return The count of addedValues.
   */
  int getAddedValuesCount();
  /**
   * <pre>
   * this is specific to field data type list
   * will have the new values added to the list
   * </pre>
   *
   * <code>repeated string added_values = 5 [json_name = "addedValues"];</code>
   * @param index The index of the element to return.
   * @return The addedValues at the given index.
   */
  java.lang.String getAddedValues(int index);
  /**
   * <pre>
   * this is specific to field data type list
   * will have the new values added to the list
   * </pre>
   *
   * <code>repeated string added_values = 5 [json_name = "addedValues"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the addedValues at the given index.
   */
  com.google.protobuf.ByteString
      getAddedValuesBytes(int index);

  /**
   * <pre>
   * this is specific to field data type list
   * will have the values removed from the list
   * </pre>
   *
   * <code>repeated string removed_values = 6 [json_name = "removedValues"];</code>
   * @return A list containing the removedValues.
   */
  java.util.List<java.lang.String>
      getRemovedValuesList();
  /**
   * <pre>
   * this is specific to field data type list
   * will have the values removed from the list
   * </pre>
   *
   * <code>repeated string removed_values = 6 [json_name = "removedValues"];</code>
   * @return The count of removedValues.
   */
  int getRemovedValuesCount();
  /**
   * <pre>
   * this is specific to field data type list
   * will have the values removed from the list
   * </pre>
   *
   * <code>repeated string removed_values = 6 [json_name = "removedValues"];</code>
   * @param index The index of the element to return.
   * @return The removedValues at the given index.
   */
  java.lang.String getRemovedValues(int index);
  /**
   * <pre>
   * this is specific to field data type list
   * will have the values removed from the list
   * </pre>
   *
   * <code>repeated string removed_values = 6 [json_name = "removedValues"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the removedValues at the given index.
   */
  com.google.protobuf.ByteString
      getRemovedValuesBytes(int index);
}
