// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/timeline/rpc/model.proto

package com.leftbin.commons.proto.v1.timeline.rpc;

/**
 * <pre>
 * time line of resource is list of activity
 * and each activity holds the information of the state change happened on the resource
 * </pre>
 *
 * Protobuf type {@code leftbin.commons.proto.v1.timeline.rpc.Activity}
 */
public final class Activity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:leftbin.commons.proto.v1.timeline.rpc.Activity)
    ActivityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Activity.newBuilder() to construct.
  private Activity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Activity() {
    activityId_ = "";
    activityType_ = 0;
    actor_ = "";
    resourceId_ = "";
    resourceType_ = "";
    updates_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Activity();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_Activity_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_Activity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.leftbin.commons.proto.v1.timeline.rpc.Activity.class, com.leftbin.commons.proto.v1.timeline.rpc.Activity.Builder.class);
  }

  public static final int ACTIVITY_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object activityId_;
  /**
   * <pre>
   * unique identifier of the activity
   * </pre>
   *
   * <code>string activity_id = 1 [json_name = "activityId"];</code>
   * @return The activityId.
   */
  @java.lang.Override
  public java.lang.String getActivityId() {
    java.lang.Object ref = activityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      activityId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unique identifier of the activity
   * </pre>
   *
   * <code>string activity_id = 1 [json_name = "activityId"];</code>
   * @return The bytes for activityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActivityIdBytes() {
    java.lang.Object ref = activityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      activityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTIVITY_TYPE_FIELD_NUMBER = 2;
  private int activityType_;
  /**
   * <pre>
   * type of the activity to identity the crud operation happened on the resource
   * </pre>
   *
   * <code>.leftbin.commons.proto.v1.timeline.enums.ActivityType activity_type = 2 [json_name = "activityType"];</code>
   * @return The enum numeric value on the wire for activityType.
   */
  @java.lang.Override public int getActivityTypeValue() {
    return activityType_;
  }
  /**
   * <pre>
   * type of the activity to identity the crud operation happened on the resource
   * </pre>
   *
   * <code>.leftbin.commons.proto.v1.timeline.enums.ActivityType activity_type = 2 [json_name = "activityType"];</code>
   * @return The activityType.
   */
  @java.lang.Override public com.leftbin.commons.proto.v1.timeline.enums.ActivityType getActivityType() {
    @SuppressWarnings("deprecation")
    com.leftbin.commons.proto.v1.timeline.enums.ActivityType result = com.leftbin.commons.proto.v1.timeline.enums.ActivityType.valueOf(activityType_);
    return result == null ? com.leftbin.commons.proto.v1.timeline.enums.ActivityType.UNRECOGNIZED : result;
  }

  public static final int ACTOR_FIELD_NUMBER = 3;
  private volatile java.lang.Object actor_;
  /**
   * <pre>
   * email id of the user who has done the activity
   * </pre>
   *
   * <code>string actor = 3 [json_name = "actor"];</code>
   * @return The actor.
   */
  @java.lang.Override
  public java.lang.String getActor() {
    java.lang.Object ref = actor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * email id of the user who has done the activity
   * </pre>
   *
   * <code>string actor = 3 [json_name = "actor"];</code>
   * @return The bytes for actor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorBytes() {
    java.lang.Object ref = actor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CRE_TS_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp creTs_;
  /**
   * <pre>
   * time stamp of when the activity was done
   * </pre>
   *
   * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
   * @return Whether the creTs field is set.
   */
  @java.lang.Override
  public boolean hasCreTs() {
    return creTs_ != null;
  }
  /**
   * <pre>
   * time stamp of when the activity was done
   * </pre>
   *
   * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
   * @return The creTs.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreTs() {
    return creTs_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creTs_;
  }
  /**
   * <pre>
   * time stamp of when the activity was done
   * </pre>
   *
   * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreTsOrBuilder() {
    return getCreTs();
  }

  public static final int RESOURCE_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object resourceId_;
  /**
   * <pre>
   * unique identifier of the resource the activity belongs to
   * </pre>
   *
   * <code>string resource_id = 5 [json_name = "resourceId"];</code>
   * @return The resourceId.
   */
  @java.lang.Override
  public java.lang.String getResourceId() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unique identifier of the resource the activity belongs to
   * </pre>
   *
   * <code>string resource_id = 5 [json_name = "resourceId"];</code>
   * @return The bytes for resourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceIdBytes() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOURCE_TYPE_FIELD_NUMBER = 6;
  private volatile java.lang.Object resourceType_;
  /**
   * <pre>
   * type of the resource the activity belongs to.
   * </pre>
   *
   * <code>string resource_type = 6 [json_name = "resourceType"];</code>
   * @return The resourceType.
   */
  @java.lang.Override
  public java.lang.String getResourceType() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * type of the resource the activity belongs to.
   * </pre>
   *
   * <code>string resource_type = 6 [json_name = "resourceType"];</code>
   * @return The bytes for resourceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceTypeBytes() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATES_FIELD_NUMBER = 7;
  private java.util.List<com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate> updates_;
  /**
   * <pre>
   * this is valid in case of activity type updates.
   * to capture the updates happened on specific fields and there
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
   */
  @java.lang.Override
  public java.util.List<com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate> getUpdatesList() {
    return updates_;
  }
  /**
   * <pre>
   * this is valid in case of activity type updates.
   * to capture the updates happened on specific fields and there
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdateOrBuilder> 
      getUpdatesOrBuilderList() {
    return updates_;
  }
  /**
   * <pre>
   * this is valid in case of activity type updates.
   * to capture the updates happened on specific fields and there
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
   */
  @java.lang.Override
  public int getUpdatesCount() {
    return updates_.size();
  }
  /**
   * <pre>
   * this is valid in case of activity type updates.
   * to capture the updates happened on specific fields and there
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate getUpdates(int index) {
    return updates_.get(index);
  }
  /**
   * <pre>
   * this is valid in case of activity type updates.
   * to capture the updates happened on specific fields and there
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdateOrBuilder getUpdatesOrBuilder(
      int index) {
    return updates_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(activityId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, activityId_);
    }
    if (activityType_ != com.leftbin.commons.proto.v1.timeline.enums.ActivityType.ACTIVITY_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, activityType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(actor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, actor_);
    }
    if (creTs_ != null) {
      output.writeMessage(4, getCreTs());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, resourceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, resourceType_);
    }
    for (int i = 0; i < updates_.size(); i++) {
      output.writeMessage(7, updates_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(activityId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, activityId_);
    }
    if (activityType_ != com.leftbin.commons.proto.v1.timeline.enums.ActivityType.ACTIVITY_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, activityType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(actor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, actor_);
    }
    if (creTs_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCreTs());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, resourceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, resourceType_);
    }
    for (int i = 0; i < updates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, updates_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.leftbin.commons.proto.v1.timeline.rpc.Activity)) {
      return super.equals(obj);
    }
    com.leftbin.commons.proto.v1.timeline.rpc.Activity other = (com.leftbin.commons.proto.v1.timeline.rpc.Activity) obj;

    if (!getActivityId()
        .equals(other.getActivityId())) return false;
    if (activityType_ != other.activityType_) return false;
    if (!getActor()
        .equals(other.getActor())) return false;
    if (hasCreTs() != other.hasCreTs()) return false;
    if (hasCreTs()) {
      if (!getCreTs()
          .equals(other.getCreTs())) return false;
    }
    if (!getResourceId()
        .equals(other.getResourceId())) return false;
    if (!getResourceType()
        .equals(other.getResourceType())) return false;
    if (!getUpdatesList()
        .equals(other.getUpdatesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTIVITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getActivityId().hashCode();
    hash = (37 * hash) + ACTIVITY_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + activityType_;
    hash = (37 * hash) + ACTOR_FIELD_NUMBER;
    hash = (53 * hash) + getActor().hashCode();
    if (hasCreTs()) {
      hash = (37 * hash) + CRE_TS_FIELD_NUMBER;
      hash = (53 * hash) + getCreTs().hashCode();
    }
    hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getResourceId().hashCode();
    hash = (37 * hash) + RESOURCE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getResourceType().hashCode();
    if (getUpdatesCount() > 0) {
      hash = (37 * hash) + UPDATES_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.leftbin.commons.proto.v1.timeline.rpc.Activity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * time line of resource is list of activity
   * and each activity holds the information of the state change happened on the resource
   * </pre>
   *
   * Protobuf type {@code leftbin.commons.proto.v1.timeline.rpc.Activity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:leftbin.commons.proto.v1.timeline.rpc.Activity)
      com.leftbin.commons.proto.v1.timeline.rpc.ActivityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_Activity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_Activity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leftbin.commons.proto.v1.timeline.rpc.Activity.class, com.leftbin.commons.proto.v1.timeline.rpc.Activity.Builder.class);
    }

    // Construct using com.leftbin.commons.proto.v1.timeline.rpc.Activity.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      activityId_ = "";

      activityType_ = 0;

      actor_ = "";

      if (creTsBuilder_ == null) {
        creTs_ = null;
      } else {
        creTs_ = null;
        creTsBuilder_ = null;
      }
      resourceId_ = "";

      resourceType_ = "";

      if (updatesBuilder_ == null) {
        updates_ = java.util.Collections.emptyList();
      } else {
        updates_ = null;
        updatesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_Activity_descriptor;
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.timeline.rpc.Activity getDefaultInstanceForType() {
      return com.leftbin.commons.proto.v1.timeline.rpc.Activity.getDefaultInstance();
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.timeline.rpc.Activity build() {
      com.leftbin.commons.proto.v1.timeline.rpc.Activity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.timeline.rpc.Activity buildPartial() {
      com.leftbin.commons.proto.v1.timeline.rpc.Activity result = new com.leftbin.commons.proto.v1.timeline.rpc.Activity(this);
      int from_bitField0_ = bitField0_;
      result.activityId_ = activityId_;
      result.activityType_ = activityType_;
      result.actor_ = actor_;
      if (creTsBuilder_ == null) {
        result.creTs_ = creTs_;
      } else {
        result.creTs_ = creTsBuilder_.build();
      }
      result.resourceId_ = resourceId_;
      result.resourceType_ = resourceType_;
      if (updatesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          updates_ = java.util.Collections.unmodifiableList(updates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.updates_ = updates_;
      } else {
        result.updates_ = updatesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.leftbin.commons.proto.v1.timeline.rpc.Activity) {
        return mergeFrom((com.leftbin.commons.proto.v1.timeline.rpc.Activity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.leftbin.commons.proto.v1.timeline.rpc.Activity other) {
      if (other == com.leftbin.commons.proto.v1.timeline.rpc.Activity.getDefaultInstance()) return this;
      if (!other.getActivityId().isEmpty()) {
        activityId_ = other.activityId_;
        onChanged();
      }
      if (other.activityType_ != 0) {
        setActivityTypeValue(other.getActivityTypeValue());
      }
      if (!other.getActor().isEmpty()) {
        actor_ = other.actor_;
        onChanged();
      }
      if (other.hasCreTs()) {
        mergeCreTs(other.getCreTs());
      }
      if (!other.getResourceId().isEmpty()) {
        resourceId_ = other.resourceId_;
        onChanged();
      }
      if (!other.getResourceType().isEmpty()) {
        resourceType_ = other.resourceType_;
        onChanged();
      }
      if (updatesBuilder_ == null) {
        if (!other.updates_.isEmpty()) {
          if (updates_.isEmpty()) {
            updates_ = other.updates_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUpdatesIsMutable();
            updates_.addAll(other.updates_);
          }
          onChanged();
        }
      } else {
        if (!other.updates_.isEmpty()) {
          if (updatesBuilder_.isEmpty()) {
            updatesBuilder_.dispose();
            updatesBuilder_ = null;
            updates_ = other.updates_;
            bitField0_ = (bitField0_ & ~0x00000001);
            updatesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUpdatesFieldBuilder() : null;
          } else {
            updatesBuilder_.addAllMessages(other.updates_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              activityId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              activityType_ = input.readEnum();

              break;
            } // case 16
            case 26: {
              actor_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getCreTsFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 34
            case 42: {
              resourceId_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              resourceType_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate m =
                  input.readMessage(
                      com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.parser(),
                      extensionRegistry);
              if (updatesBuilder_ == null) {
                ensureUpdatesIsMutable();
                updates_.add(m);
              } else {
                updatesBuilder_.addMessage(m);
              }
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object activityId_ = "";
    /**
     * <pre>
     * unique identifier of the activity
     * </pre>
     *
     * <code>string activity_id = 1 [json_name = "activityId"];</code>
     * @return The activityId.
     */
    public java.lang.String getActivityId() {
      java.lang.Object ref = activityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique identifier of the activity
     * </pre>
     *
     * <code>string activity_id = 1 [json_name = "activityId"];</code>
     * @return The bytes for activityId.
     */
    public com.google.protobuf.ByteString
        getActivityIdBytes() {
      java.lang.Object ref = activityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique identifier of the activity
     * </pre>
     *
     * <code>string activity_id = 1 [json_name = "activityId"];</code>
     * @param value The activityId to set.
     * @return This builder for chaining.
     */
    public Builder setActivityId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      activityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier of the activity
     * </pre>
     *
     * <code>string activity_id = 1 [json_name = "activityId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActivityId() {
      
      activityId_ = getDefaultInstance().getActivityId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier of the activity
     * </pre>
     *
     * <code>string activity_id = 1 [json_name = "activityId"];</code>
     * @param value The bytes for activityId to set.
     * @return This builder for chaining.
     */
    public Builder setActivityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      activityId_ = value;
      onChanged();
      return this;
    }

    private int activityType_ = 0;
    /**
     * <pre>
     * type of the activity to identity the crud operation happened on the resource
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.timeline.enums.ActivityType activity_type = 2 [json_name = "activityType"];</code>
     * @return The enum numeric value on the wire for activityType.
     */
    @java.lang.Override public int getActivityTypeValue() {
      return activityType_;
    }
    /**
     * <pre>
     * type of the activity to identity the crud operation happened on the resource
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.timeline.enums.ActivityType activity_type = 2 [json_name = "activityType"];</code>
     * @param value The enum numeric value on the wire for activityType to set.
     * @return This builder for chaining.
     */
    public Builder setActivityTypeValue(int value) {
      
      activityType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * type of the activity to identity the crud operation happened on the resource
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.timeline.enums.ActivityType activity_type = 2 [json_name = "activityType"];</code>
     * @return The activityType.
     */
    @java.lang.Override
    public com.leftbin.commons.proto.v1.timeline.enums.ActivityType getActivityType() {
      @SuppressWarnings("deprecation")
      com.leftbin.commons.proto.v1.timeline.enums.ActivityType result = com.leftbin.commons.proto.v1.timeline.enums.ActivityType.valueOf(activityType_);
      return result == null ? com.leftbin.commons.proto.v1.timeline.enums.ActivityType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * type of the activity to identity the crud operation happened on the resource
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.timeline.enums.ActivityType activity_type = 2 [json_name = "activityType"];</code>
     * @param value The activityType to set.
     * @return This builder for chaining.
     */
    public Builder setActivityType(com.leftbin.commons.proto.v1.timeline.enums.ActivityType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      activityType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * type of the activity to identity the crud operation happened on the resource
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.timeline.enums.ActivityType activity_type = 2 [json_name = "activityType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActivityType() {
      
      activityType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object actor_ = "";
    /**
     * <pre>
     * email id of the user who has done the activity
     * </pre>
     *
     * <code>string actor = 3 [json_name = "actor"];</code>
     * @return The actor.
     */
    public java.lang.String getActor() {
      java.lang.Object ref = actor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * email id of the user who has done the activity
     * </pre>
     *
     * <code>string actor = 3 [json_name = "actor"];</code>
     * @return The bytes for actor.
     */
    public com.google.protobuf.ByteString
        getActorBytes() {
      java.lang.Object ref = actor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * email id of the user who has done the activity
     * </pre>
     *
     * <code>string actor = 3 [json_name = "actor"];</code>
     * @param value The actor to set.
     * @return This builder for chaining.
     */
    public Builder setActor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      actor_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * email id of the user who has done the activity
     * </pre>
     *
     * <code>string actor = 3 [json_name = "actor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActor() {
      
      actor_ = getDefaultInstance().getActor();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * email id of the user who has done the activity
     * </pre>
     *
     * <code>string actor = 3 [json_name = "actor"];</code>
     * @param value The bytes for actor to set.
     * @return This builder for chaining.
     */
    public Builder setActorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      actor_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp creTs_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> creTsBuilder_;
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     * @return Whether the creTs field is set.
     */
    public boolean hasCreTs() {
      return creTsBuilder_ != null || creTs_ != null;
    }
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     * @return The creTs.
     */
    public com.google.protobuf.Timestamp getCreTs() {
      if (creTsBuilder_ == null) {
        return creTs_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creTs_;
      } else {
        return creTsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     */
    public Builder setCreTs(com.google.protobuf.Timestamp value) {
      if (creTsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        creTs_ = value;
        onChanged();
      } else {
        creTsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     */
    public Builder setCreTs(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (creTsBuilder_ == null) {
        creTs_ = builderForValue.build();
        onChanged();
      } else {
        creTsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     */
    public Builder mergeCreTs(com.google.protobuf.Timestamp value) {
      if (creTsBuilder_ == null) {
        if (creTs_ != null) {
          creTs_ =
            com.google.protobuf.Timestamp.newBuilder(creTs_).mergeFrom(value).buildPartial();
        } else {
          creTs_ = value;
        }
        onChanged();
      } else {
        creTsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     */
    public Builder clearCreTs() {
      if (creTsBuilder_ == null) {
        creTs_ = null;
        onChanged();
      } else {
        creTs_ = null;
        creTsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreTsBuilder() {
      
      onChanged();
      return getCreTsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreTsOrBuilder() {
      if (creTsBuilder_ != null) {
        return creTsBuilder_.getMessageOrBuilder();
      } else {
        return creTs_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : creTs_;
      }
    }
    /**
     * <pre>
     * time stamp of when the activity was done
     * </pre>
     *
     * <code>.google.protobuf.Timestamp cre_ts = 4 [json_name = "creTs"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreTsFieldBuilder() {
      if (creTsBuilder_ == null) {
        creTsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreTs(),
                getParentForChildren(),
                isClean());
        creTs_ = null;
      }
      return creTsBuilder_;
    }

    private java.lang.Object resourceId_ = "";
    /**
     * <pre>
     * unique identifier of the resource the activity belongs to
     * </pre>
     *
     * <code>string resource_id = 5 [json_name = "resourceId"];</code>
     * @return The resourceId.
     */
    public java.lang.String getResourceId() {
      java.lang.Object ref = resourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique identifier of the resource the activity belongs to
     * </pre>
     *
     * <code>string resource_id = 5 [json_name = "resourceId"];</code>
     * @return The bytes for resourceId.
     */
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique identifier of the resource the activity belongs to
     * </pre>
     *
     * <code>string resource_id = 5 [json_name = "resourceId"];</code>
     * @param value The resourceId to set.
     * @return This builder for chaining.
     */
    public Builder setResourceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resourceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier of the resource the activity belongs to
     * </pre>
     *
     * <code>string resource_id = 5 [json_name = "resourceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceId() {
      
      resourceId_ = getDefaultInstance().getResourceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier of the resource the activity belongs to
     * </pre>
     *
     * <code>string resource_id = 5 [json_name = "resourceId"];</code>
     * @param value The bytes for resourceId to set.
     * @return This builder for chaining.
     */
    public Builder setResourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resourceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object resourceType_ = "";
    /**
     * <pre>
     * type of the resource the activity belongs to.
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @return The resourceType.
     */
    public java.lang.String getResourceType() {
      java.lang.Object ref = resourceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * type of the resource the activity belongs to.
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @return The bytes for resourceType.
     */
    public com.google.protobuf.ByteString
        getResourceTypeBytes() {
      java.lang.Object ref = resourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * type of the resource the activity belongs to.
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @param value The resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resourceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * type of the resource the activity belongs to.
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceType() {
      
      resourceType_ = getDefaultInstance().getResourceType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * type of the resource the activity belongs to.
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @param value The bytes for resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resourceType_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate> updates_ =
      java.util.Collections.emptyList();
    private void ensureUpdatesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        updates_ = new java.util.ArrayList<com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate>(updates_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdateOrBuilder> updatesBuilder_;

    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate> getUpdatesList() {
      if (updatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(updates_);
      } else {
        return updatesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public int getUpdatesCount() {
      if (updatesBuilder_ == null) {
        return updates_.size();
      } else {
        return updatesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate getUpdates(int index) {
      if (updatesBuilder_ == null) {
        return updates_.get(index);
      } else {
        return updatesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder setUpdates(
        int index, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate value) {
      if (updatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatesIsMutable();
        updates_.set(index, value);
        onChanged();
      } else {
        updatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder setUpdates(
        int index, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder builderForValue) {
      if (updatesBuilder_ == null) {
        ensureUpdatesIsMutable();
        updates_.set(index, builderForValue.build());
        onChanged();
      } else {
        updatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder addUpdates(com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate value) {
      if (updatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatesIsMutable();
        updates_.add(value);
        onChanged();
      } else {
        updatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder addUpdates(
        int index, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate value) {
      if (updatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatesIsMutable();
        updates_.add(index, value);
        onChanged();
      } else {
        updatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder addUpdates(
        com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder builderForValue) {
      if (updatesBuilder_ == null) {
        ensureUpdatesIsMutable();
        updates_.add(builderForValue.build());
        onChanged();
      } else {
        updatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder addUpdates(
        int index, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder builderForValue) {
      if (updatesBuilder_ == null) {
        ensureUpdatesIsMutable();
        updates_.add(index, builderForValue.build());
        onChanged();
      } else {
        updatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder addAllUpdates(
        java.lang.Iterable<? extends com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate> values) {
      if (updatesBuilder_ == null) {
        ensureUpdatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, updates_);
        onChanged();
      } else {
        updatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder clearUpdates() {
      if (updatesBuilder_ == null) {
        updates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        updatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public Builder removeUpdates(int index) {
      if (updatesBuilder_ == null) {
        ensureUpdatesIsMutable();
        updates_.remove(index);
        onChanged();
      } else {
        updatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder getUpdatesBuilder(
        int index) {
      return getUpdatesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdateOrBuilder getUpdatesOrBuilder(
        int index) {
      if (updatesBuilder_ == null) {
        return updates_.get(index);  } else {
        return updatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public java.util.List<? extends com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdateOrBuilder> 
         getUpdatesOrBuilderList() {
      if (updatesBuilder_ != null) {
        return updatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(updates_);
      }
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder addUpdatesBuilder() {
      return getUpdatesFieldBuilder().addBuilder(
          com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.getDefaultInstance());
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder addUpdatesBuilder(
        int index) {
      return getUpdatesFieldBuilder().addBuilder(
          index, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.getDefaultInstance());
    }
    /**
     * <pre>
     * this is valid in case of activity type updates.
     * to capture the updates happened on specific fields and there
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate updates = 7 [json_name = "updates"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder> 
         getUpdatesBuilderList() {
      return getUpdatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdateOrBuilder> 
        getUpdatesFieldBuilder() {
      if (updatesBuilder_ == null) {
        updatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdate.Builder, com.leftbin.commons.proto.v1.timeline.rpc.ActivityUpdateOrBuilder>(
                updates_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        updates_ = null;
      }
      return updatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:leftbin.commons.proto.v1.timeline.rpc.Activity)
  }

  // @@protoc_insertion_point(class_scope:leftbin.commons.proto.v1.timeline.rpc.Activity)
  private static final com.leftbin.commons.proto.v1.timeline.rpc.Activity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.leftbin.commons.proto.v1.timeline.rpc.Activity();
  }

  public static com.leftbin.commons.proto.v1.timeline.rpc.Activity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Activity>
      PARSER = new com.google.protobuf.AbstractParser<Activity>() {
    @java.lang.Override
    public Activity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Activity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Activity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.leftbin.commons.proto.v1.timeline.rpc.Activity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

