// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/timeline/rpc/model.proto

package com.leftbin.commons.proto.v1.timeline.rpc;

/**
 * <pre>
 * input to get paginated activity list
 * </pre>
 *
 * Protobuf type {@code leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput}
 */
public final class ListActivityByResourceTypeAndResourceIdInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput)
    ListActivityByResourceTypeAndResourceIdInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListActivityByResourceTypeAndResourceIdInput.newBuilder() to construct.
  private ListActivityByResourceTypeAndResourceIdInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListActivityByResourceTypeAndResourceIdInput() {
    resourceId_ = "";
    resourceType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListActivityByResourceTypeAndResourceIdInput();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_ListActivityByResourceTypeAndResourceIdInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_ListActivityByResourceTypeAndResourceIdInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput.class, com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput.Builder.class);
  }

  public static final int RESOURCE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourceId_ = "";
  /**
   * <pre>
   * unique identifier of the resource
   * </pre>
   *
   * <code>string resource_id = 1 [json_name = "resourceId"];</code>
   * @return The resourceId.
   */
  @java.lang.Override
  public java.lang.String getResourceId() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unique identifier of the resource
   * </pre>
   *
   * <code>string resource_id = 1 [json_name = "resourceId"];</code>
   * @return The bytes for resourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceIdBytes() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOURCE_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourceType_ = "";
  /**
   * <pre>
   * type of the resource
   * </pre>
   *
   * <code>string resource_type = 2 [json_name = "resourceType"];</code>
   * @return The resourceType.
   */
  @java.lang.Override
  public java.lang.String getResourceType() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * type of the resource
   * </pre>
   *
   * <code>string resource_type = 2 [json_name = "resourceType"];</code>
   * @return The bytes for resourceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceTypeBytes() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_INFO_FIELD_NUMBER = 3;
  private com.leftbin.commons.proto.v1.pagination.PageInfo pageInfo_;
  /**
   * <pre>
   * pagination input
   * </pre>
   *
   * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
   * @return Whether the pageInfo field is set.
   */
  @java.lang.Override
  public boolean hasPageInfo() {
    return pageInfo_ != null;
  }
  /**
   * <pre>
   * pagination input
   * </pre>
   *
   * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
   * @return The pageInfo.
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.pagination.PageInfo getPageInfo() {
    return pageInfo_ == null ? com.leftbin.commons.proto.v1.pagination.PageInfo.getDefaultInstance() : pageInfo_;
  }
  /**
   * <pre>
   * pagination input
   * </pre>
   *
   * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.pagination.PageInfoOrBuilder getPageInfoOrBuilder() {
    return pageInfo_ == null ? com.leftbin.commons.proto.v1.pagination.PageInfo.getDefaultInstance() : pageInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resourceType_);
    }
    if (pageInfo_ != null) {
      output.writeMessage(3, getPageInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resourceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resourceType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resourceType_);
    }
    if (pageInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPageInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput)) {
      return super.equals(obj);
    }
    com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput other = (com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput) obj;

    if (!getResourceId()
        .equals(other.getResourceId())) return false;
    if (!getResourceType()
        .equals(other.getResourceType())) return false;
    if (hasPageInfo() != other.hasPageInfo()) return false;
    if (hasPageInfo()) {
      if (!getPageInfo()
          .equals(other.getPageInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getResourceId().hashCode();
    hash = (37 * hash) + RESOURCE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getResourceType().hashCode();
    if (hasPageInfo()) {
      hash = (37 * hash) + PAGE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getPageInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * input to get paginated activity list
   * </pre>
   *
   * Protobuf type {@code leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput)
      com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_ListActivityByResourceTypeAndResourceIdInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_ListActivityByResourceTypeAndResourceIdInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput.class, com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput.Builder.class);
    }

    // Construct using com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resourceId_ = "";
      resourceType_ = "";
      pageInfo_ = null;
      if (pageInfoBuilder_ != null) {
        pageInfoBuilder_.dispose();
        pageInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.leftbin.commons.proto.v1.timeline.rpc.ModelProto.internal_static_leftbin_commons_proto_v1_timeline_rpc_ListActivityByResourceTypeAndResourceIdInput_descriptor;
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput getDefaultInstanceForType() {
      return com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput.getDefaultInstance();
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput build() {
      com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput buildPartial() {
      com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput result = new com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resourceId_ = resourceId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.resourceType_ = resourceType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pageInfo_ = pageInfoBuilder_ == null
            ? pageInfo_
            : pageInfoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput) {
        return mergeFrom((com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput other) {
      if (other == com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput.getDefaultInstance()) return this;
      if (!other.getResourceId().isEmpty()) {
        resourceId_ = other.resourceId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getResourceType().isEmpty()) {
        resourceType_ = other.resourceType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasPageInfo()) {
        mergePageInfo(other.getPageInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              resourceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              resourceType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPageInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object resourceId_ = "";
    /**
     * <pre>
     * unique identifier of the resource
     * </pre>
     *
     * <code>string resource_id = 1 [json_name = "resourceId"];</code>
     * @return The resourceId.
     */
    public java.lang.String getResourceId() {
      java.lang.Object ref = resourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique identifier of the resource
     * </pre>
     *
     * <code>string resource_id = 1 [json_name = "resourceId"];</code>
     * @return The bytes for resourceId.
     */
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique identifier of the resource
     * </pre>
     *
     * <code>string resource_id = 1 [json_name = "resourceId"];</code>
     * @param value The resourceId to set.
     * @return This builder for chaining.
     */
    public Builder setResourceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier of the resource
     * </pre>
     *
     * <code>string resource_id = 1 [json_name = "resourceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceId() {
      resourceId_ = getDefaultInstance().getResourceId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique identifier of the resource
     * </pre>
     *
     * <code>string resource_id = 1 [json_name = "resourceId"];</code>
     * @param value The bytes for resourceId to set.
     * @return This builder for chaining.
     */
    public Builder setResourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object resourceType_ = "";
    /**
     * <pre>
     * type of the resource
     * </pre>
     *
     * <code>string resource_type = 2 [json_name = "resourceType"];</code>
     * @return The resourceType.
     */
    public java.lang.String getResourceType() {
      java.lang.Object ref = resourceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * type of the resource
     * </pre>
     *
     * <code>string resource_type = 2 [json_name = "resourceType"];</code>
     * @return The bytes for resourceType.
     */
    public com.google.protobuf.ByteString
        getResourceTypeBytes() {
      java.lang.Object ref = resourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * type of the resource
     * </pre>
     *
     * <code>string resource_type = 2 [json_name = "resourceType"];</code>
     * @param value The resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourceType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * type of the resource
     * </pre>
     *
     * <code>string resource_type = 2 [json_name = "resourceType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceType() {
      resourceType_ = getDefaultInstance().getResourceType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * type of the resource
     * </pre>
     *
     * <code>string resource_type = 2 [json_name = "resourceType"];</code>
     * @param value The bytes for resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourceType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.leftbin.commons.proto.v1.pagination.PageInfo pageInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.leftbin.commons.proto.v1.pagination.PageInfo, com.leftbin.commons.proto.v1.pagination.PageInfo.Builder, com.leftbin.commons.proto.v1.pagination.PageInfoOrBuilder> pageInfoBuilder_;
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     * @return Whether the pageInfo field is set.
     */
    public boolean hasPageInfo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     * @return The pageInfo.
     */
    public com.leftbin.commons.proto.v1.pagination.PageInfo getPageInfo() {
      if (pageInfoBuilder_ == null) {
        return pageInfo_ == null ? com.leftbin.commons.proto.v1.pagination.PageInfo.getDefaultInstance() : pageInfo_;
      } else {
        return pageInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     */
    public Builder setPageInfo(com.leftbin.commons.proto.v1.pagination.PageInfo value) {
      if (pageInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageInfo_ = value;
      } else {
        pageInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     */
    public Builder setPageInfo(
        com.leftbin.commons.proto.v1.pagination.PageInfo.Builder builderForValue) {
      if (pageInfoBuilder_ == null) {
        pageInfo_ = builderForValue.build();
      } else {
        pageInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     */
    public Builder mergePageInfo(com.leftbin.commons.proto.v1.pagination.PageInfo value) {
      if (pageInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          pageInfo_ != null &&
          pageInfo_ != com.leftbin.commons.proto.v1.pagination.PageInfo.getDefaultInstance()) {
          getPageInfoBuilder().mergeFrom(value);
        } else {
          pageInfo_ = value;
        }
      } else {
        pageInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     */
    public Builder clearPageInfo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pageInfo_ = null;
      if (pageInfoBuilder_ != null) {
        pageInfoBuilder_.dispose();
        pageInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     */
    public com.leftbin.commons.proto.v1.pagination.PageInfo.Builder getPageInfoBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPageInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     */
    public com.leftbin.commons.proto.v1.pagination.PageInfoOrBuilder getPageInfoOrBuilder() {
      if (pageInfoBuilder_ != null) {
        return pageInfoBuilder_.getMessageOrBuilder();
      } else {
        return pageInfo_ == null ?
            com.leftbin.commons.proto.v1.pagination.PageInfo.getDefaultInstance() : pageInfo_;
      }
    }
    /**
     * <pre>
     * pagination input
     * </pre>
     *
     * <code>.leftbin.commons.proto.v1.pagination.PageInfo page_info = 3 [json_name = "pageInfo"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.leftbin.commons.proto.v1.pagination.PageInfo, com.leftbin.commons.proto.v1.pagination.PageInfo.Builder, com.leftbin.commons.proto.v1.pagination.PageInfoOrBuilder> 
        getPageInfoFieldBuilder() {
      if (pageInfoBuilder_ == null) {
        pageInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.leftbin.commons.proto.v1.pagination.PageInfo, com.leftbin.commons.proto.v1.pagination.PageInfo.Builder, com.leftbin.commons.proto.v1.pagination.PageInfoOrBuilder>(
                getPageInfo(),
                getParentForChildren(),
                isClean());
        pageInfo_ = null;
      }
      return pageInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput)
  }

  // @@protoc_insertion_point(class_scope:leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput)
  private static final com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput();
  }

  public static com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListActivityByResourceTypeAndResourceIdInput>
      PARSER = new com.google.protobuf.AbstractParser<ListActivityByResourceTypeAndResourceIdInput>() {
    @java.lang.Override
    public ListActivityByResourceTypeAndResourceIdInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListActivityByResourceTypeAndResourceIdInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListActivityByResourceTypeAndResourceIdInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.leftbin.commons.proto.v1.timeline.rpc.ListActivityByResourceTypeAndResourceIdInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

