// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/audit/model.proto

package com.leftbin.commons.proto.v1.audit;

public final class ModelProto {
  private ModelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_leftbin_commons_proto_v1_audit_SysAudit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_leftbin_commons_proto_v1_audit_SysAudit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*leftbin/commons/proto/v1/audit/model.p" +
      "roto\022\036leftbin.commons.proto.v1.audit\032\037go" +
      "ogle/protobuf/timestamp.proto\"\335\001\n\010SysAud" +
      "it\022\035\n\ncreated_by\030\001 \001(\tR\tcreatedBy\0229\n\ncre" +
      "ated_at\030\002 \001(\0132\032.google.protobuf.Timestam" +
      "pR\tcreatedAt\022\035\n\nupdated_by\030\003 \001(\tR\tupdate" +
      "dBy\0229\n\nupdated_at\030\004 \001(\0132\032.google.protobu" +
      "f.TimestampR\tupdatedAt\022\035\n\nevent_type\030\005 \001" +
      "(\tR\teventTypeB\224\002\n\"com.leftbin.commons.pr" +
      "oto.v1.auditB\nModelProtoP\001ZDgithub.com/l" +
      "eftbin/proto-commons/zzgo/leftbin/common" +
      "s/proto/v1/audit\242\002\005LCPVA\252\002\036Leftbin.Commo" +
      "ns.Proto.V1.Audit\312\002\036Leftbin\\Commons\\Prot" +
      "o\\V1\\Audit\342\002*Leftbin\\Commons\\Proto\\V1\\Au" +
      "dit\\GPBMetadata\352\002\"Leftbin::Commons::Prot" +
      "o::V1::Auditb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_leftbin_commons_proto_v1_audit_SysAudit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_leftbin_commons_proto_v1_audit_SysAudit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_leftbin_commons_proto_v1_audit_SysAudit_descriptor,
        new java.lang.String[] { "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt", "EventType", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
