// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/kubernetes/model.proto

package com.leftbin.commons.proto.v1.kubernetes;

public interface ContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.kubernetes.Container)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string image = 2 [json_name = "image"];</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>string image = 2 [json_name = "image"];</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerPort ports = 3 [json_name = "ports"];</code>
   */
  java.util.List<com.leftbin.commons.proto.v1.kubernetes.ContainerPort> 
      getPortsList();
  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerPort ports = 3 [json_name = "ports"];</code>
   */
  com.leftbin.commons.proto.v1.kubernetes.ContainerPort getPorts(int index);
  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerPort ports = 3 [json_name = "ports"];</code>
   */
  int getPortsCount();
  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerPort ports = 3 [json_name = "ports"];</code>
   */
  java.util.List<? extends com.leftbin.commons.proto.v1.kubernetes.ContainerPortOrBuilder> 
      getPortsOrBuilderList();
  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerPort ports = 3 [json_name = "ports"];</code>
   */
  com.leftbin.commons.proto.v1.kubernetes.ContainerPortOrBuilder getPortsOrBuilder(
      int index);

  /**
   * <code>.leftbin.commons.proto.v1.kubernetes.ContainerResources resources = 4 [json_name = "resources"];</code>
   * @return Whether the resources field is set.
   */
  boolean hasResources();
  /**
   * <code>.leftbin.commons.proto.v1.kubernetes.ContainerResources resources = 4 [json_name = "resources"];</code>
   * @return The resources.
   */
  com.leftbin.commons.proto.v1.kubernetes.ContainerResources getResources();
  /**
   * <code>.leftbin.commons.proto.v1.kubernetes.ContainerResources resources = 4 [json_name = "resources"];</code>
   */
  com.leftbin.commons.proto.v1.kubernetes.ContainerResourcesOrBuilder getResourcesOrBuilder();

  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerEnvVar env = 5 [json_name = "env"];</code>
   */
  java.util.List<com.leftbin.commons.proto.v1.kubernetes.ContainerEnvVar> 
      getEnvList();
  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerEnvVar env = 5 [json_name = "env"];</code>
   */
  com.leftbin.commons.proto.v1.kubernetes.ContainerEnvVar getEnv(int index);
  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerEnvVar env = 5 [json_name = "env"];</code>
   */
  int getEnvCount();
  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerEnvVar env = 5 [json_name = "env"];</code>
   */
  java.util.List<? extends com.leftbin.commons.proto.v1.kubernetes.ContainerEnvVarOrBuilder> 
      getEnvOrBuilderList();
  /**
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.ContainerEnvVar env = 5 [json_name = "env"];</code>
   */
  com.leftbin.commons.proto.v1.kubernetes.ContainerEnvVarOrBuilder getEnvOrBuilder(
      int index);
}
