// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/network/dns/record/rpc/enums/enums.proto

package com.leftbin.commons.proto.v1.network.dns.record.rpc.enums;

public final class EnumsProto {
  private EnumsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nAleftbin/commons/proto/v1/network/dns/r" +
      "ecord/rpc/enums/enums.proto\0225leftbin.com" +
      "mons.proto.v1.network.dns.record.rpc.enu" +
      "ms*\213\001\n\rDnsRecordType\022\037\n\033DNS_RECORD_TYPE_" +
      "UNSPECIFIED\020\000\022\005\n\001A\020\001\022\010\n\004AAAA\020\002\022\t\n\005ALIAS\020" +
      "\003\022\t\n\005CNAME\020\004\022\006\n\002MX\020\005\022\006\n\002NS\020\006\022\007\n\003PTR\020\007\022\007\n" +
      "\003SOA\020\010\022\007\n\003SRV\020\t\022\007\n\003TXT\020\nB\246\003\n9com.leftbin" +
      ".commons.proto.v1.network.dns.record.rpc" +
      ".enumsB\nEnumsProtoP\001Z[github.com/leftbin" +
      "/proto-commons/zzgo/leftbin/commons/prot" +
      "o/v1/network/dns/record/rpc/enums\242\002\tLCPV" +
      "NDRRE\252\0025Leftbin.Commons.Proto.V1.Network" +
      ".Dns.Record.Rpc.Enums\312\0025Leftbin\\Commons\\" +
      "Proto\\V1\\Network\\Dns\\Record\\Rpc\\Enums\342\002A" +
      "Leftbin\\Commons\\Proto\\V1\\Network\\Dns\\Rec" +
      "ord\\Rpc\\Enums\\GPBMetadata\352\002=Leftbin::Com" +
      "mons::Proto::V1::Network::Dns::Record::R" +
      "pc::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
