// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/grpc/stream/model.proto

package com.leftbin.commons.proto.v1.grpc.stream;

public interface OutputLineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.grpc.stream.OutputLine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *a string representing output of a stream operation
   * </pre>
   *
   * <code>string value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   *a string representing output of a stream operation
   * </pre>
   *
   * <code>string value = 1 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
