// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/pagination/model.proto

package com.leftbin.commons.proto.v1.pagination;

public interface PageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.pagination.PageInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num = 1 [json_name = "num"];</code>
   * @return The num.
   */
  int getNum();

  /**
   * <code>int32 size = 2 [json_name = "size"];</code>
   * @return The size.
   */
  int getSize();
}
