// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/network/dns/domain/rpc/model.proto

package com.leftbin.commons.proto.v1.network.dns.domain.rpc;

public interface DnsDomainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.network.dns.domain.rpc.DnsDomain)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * domain name example.com
   * </pre>
   *
   * <code>string domain_name = 1 [json_name = "domainName"];</code>
   * @return The domainName.
   */
  java.lang.String getDomainName();
  /**
   * <pre>
   * domain name example.com
   * </pre>
   *
   * <code>string domain_name = 1 [json_name = "domainName"];</code>
   * @return The bytes for domainName.
   */
  com.google.protobuf.ByteString
      getDomainNameBytes();

  /**
   * <pre>
   * domain visibility. for private visibility internal reserved ips are added to the zone.
   * for publicly visible domains external reserved domains are added to the zone.
   * </pre>
   *
   * <code>.leftbin.commons.proto.v1.network.dns.domain.rpc.enums.DnsDomainVisibility visibility = 2 [json_name = "visibility"];</code>
   * @return The enum numeric value on the wire for visibility.
   */
  int getVisibilityValue();
  /**
   * <pre>
   * domain visibility. for private visibility internal reserved ips are added to the zone.
   * for publicly visible domains external reserved domains are added to the zone.
   * </pre>
   *
   * <code>.leftbin.commons.proto.v1.network.dns.domain.rpc.enums.DnsDomainVisibility visibility = 2 [json_name = "visibility"];</code>
   * @return The visibility.
   */
  com.leftbin.commons.proto.v1.network.dns.domain.rpc.enums.DnsDomainVisibility getVisibility();

  /**
   * <pre>
   * dns records to be added to the zone
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecord dns_records = 3 [json_name = "dnsRecords"];</code>
   */
  java.util.List<com.leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecord> 
      getDnsRecordsList();
  /**
   * <pre>
   * dns records to be added to the zone
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecord dns_records = 3 [json_name = "dnsRecords"];</code>
   */
  com.leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecord getDnsRecords(int index);
  /**
   * <pre>
   * dns records to be added to the zone
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecord dns_records = 3 [json_name = "dnsRecords"];</code>
   */
  int getDnsRecordsCount();
  /**
   * <pre>
   * dns records to be added to the zone
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecord dns_records = 3 [json_name = "dnsRecords"];</code>
   */
  java.util.List<? extends com.leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecordOrBuilder> 
      getDnsRecordsOrBuilderList();
  /**
   * <pre>
   * dns records to be added to the zone
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecord dns_records = 3 [json_name = "dnsRecords"];</code>
   */
  com.leftbin.commons.proto.v1.network.dns.record.rpc.DnsRecordOrBuilder getDnsRecordsOrBuilder(
      int index);
}
