// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/kubernetes/resource/pod.proto

package com.leftbin.commons.proto.v1.kubernetes.resource;

public interface PodContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leftbin.commons.proto.v1.kubernetes.resource.PodContainer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *name of the container
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *name of the container
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *image used for the container
   * </pre>
   *
   * <code>string image = 2 [json_name = "image"];</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <pre>
   *image used for the container
   * </pre>
   *
   * <code>string image = 2 [json_name = "image"];</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <pre>
   *a container can be in running, waiting or terminated status.
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   *a container can be in running, waiting or terminated status.
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   *reason for the current status of the container.
   *this is only relevant for waiting and terminated statuses.
   * </pre>
   *
   * <code>string status_reason = 4 [json_name = "statusReason"];</code>
   * @return The statusReason.
   */
  java.lang.String getStatusReason();
  /**
   * <pre>
   *reason for the current status of the container.
   *this is only relevant for waiting and terminated statuses.
   * </pre>
   *
   * <code>string status_reason = 4 [json_name = "statusReason"];</code>
   * @return The bytes for statusReason.
   */
  com.google.protobuf.ByteString
      getStatusReasonBytes();

  /**
   * <pre>
   *description of the reason for the current status. this information is useful when pod in not in running state.
   * </pre>
   *
   * <code>string status_message = 5 [json_name = "statusMessage"];</code>
   * @return The statusMessage.
   */
  java.lang.String getStatusMessage();
  /**
   * <pre>
   *description of the reason for the current status. this information is useful when pod in not in running state.
   * </pre>
   *
   * <code>string status_message = 5 [json_name = "statusMessage"];</code>
   * @return The bytes for statusMessage.
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();

  /**
   * <pre>
   *number of times pod has restarted.
   * </pre>
   *
   * <code>int32 restart_count = 6 [json_name = "restartCount"];</code>
   * @return The restartCount.
   */
  int getRestartCount();
}
