// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/kubernetes/resource/pod.proto

package com.leftbin.commons.proto.v1.kubernetes.resource;

/**
 * <pre>
 * workload pods
 * </pre>
 *
 * Protobuf type {@code leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods}
 */
public final class WorkloadPods extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods)
    WorkloadPodsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkloadPods.newBuilder() to construct.
  private WorkloadPods(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkloadPods() {
    microservicePods_ = java.util.Collections.emptyList();
    postgresClusterPods_ = java.util.Collections.emptyList();
    kafkaClusterPods_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorkloadPods();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.leftbin.commons.proto.v1.kubernetes.resource.PodProto.internal_static_leftbin_commons_proto_v1_kubernetes_resource_WorkloadPods_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.leftbin.commons.proto.v1.kubernetes.resource.PodProto.internal_static_leftbin_commons_proto_v1_kubernetes_resource_WorkloadPods_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods.class, com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods.Builder.class);
  }

  public static final int MICROSERVICE_PODS_FIELD_NUMBER = 1;
  private java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> microservicePods_;
  /**
   * <pre>
   *all pods with workload=microservice in a hosting environment are included.
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
   */
  @java.lang.Override
  public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> getMicroservicePodsList() {
    return microservicePods_;
  }
  /**
   * <pre>
   *all pods with workload=microservice in a hosting environment are included.
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
      getMicroservicePodsOrBuilderList() {
    return microservicePods_;
  }
  /**
   * <pre>
   *all pods with workload=microservice in a hosting environment are included.
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
   */
  @java.lang.Override
  public int getMicroservicePodsCount() {
    return microservicePods_.size();
  }
  /**
   * <pre>
   *all pods with workload=microservice in a hosting environment are included.
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.kubernetes.resource.Pod getMicroservicePods(int index) {
    return microservicePods_.get(index);
  }
  /**
   * <pre>
   *all pods with workload=microservice in a hosting environment are included.
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder getMicroservicePodsOrBuilder(
      int index) {
    return microservicePods_.get(index);
  }

  public static final int POSTGRES_CLUSTER_PODS_FIELD_NUMBER = 2;
  private java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> postgresClusterPods_;
  /**
   * <pre>
   *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
   */
  @java.lang.Override
  public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> getPostgresClusterPodsList() {
    return postgresClusterPods_;
  }
  /**
   * <pre>
   *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
      getPostgresClusterPodsOrBuilderList() {
    return postgresClusterPods_;
  }
  /**
   * <pre>
   *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
   */
  @java.lang.Override
  public int getPostgresClusterPodsCount() {
    return postgresClusterPods_.size();
  }
  /**
   * <pre>
   *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.kubernetes.resource.Pod getPostgresClusterPods(int index) {
    return postgresClusterPods_.get(index);
  }
  /**
   * <pre>
   *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder getPostgresClusterPodsOrBuilder(
      int index) {
    return postgresClusterPods_.get(index);
  }

  public static final int KAFKA_CLUSTER_PODS_FIELD_NUMBER = 3;
  private java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> kafkaClusterPods_;
  /**
   * <pre>
   *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
   */
  @java.lang.Override
  public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> getKafkaClusterPodsList() {
    return kafkaClusterPods_;
  }
  /**
   * <pre>
   *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
      getKafkaClusterPodsOrBuilderList() {
    return kafkaClusterPods_;
  }
  /**
   * <pre>
   *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
   */
  @java.lang.Override
  public int getKafkaClusterPodsCount() {
    return kafkaClusterPods_.size();
  }
  /**
   * <pre>
   *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.kubernetes.resource.Pod getKafkaClusterPods(int index) {
    return kafkaClusterPods_.get(index);
  }
  /**
   * <pre>
   *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
   * </pre>
   *
   * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder getKafkaClusterPodsOrBuilder(
      int index) {
    return kafkaClusterPods_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < microservicePods_.size(); i++) {
      output.writeMessage(1, microservicePods_.get(i));
    }
    for (int i = 0; i < postgresClusterPods_.size(); i++) {
      output.writeMessage(2, postgresClusterPods_.get(i));
    }
    for (int i = 0; i < kafkaClusterPods_.size(); i++) {
      output.writeMessage(3, kafkaClusterPods_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < microservicePods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, microservicePods_.get(i));
    }
    for (int i = 0; i < postgresClusterPods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, postgresClusterPods_.get(i));
    }
    for (int i = 0; i < kafkaClusterPods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, kafkaClusterPods_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods)) {
      return super.equals(obj);
    }
    com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods other = (com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods) obj;

    if (!getMicroservicePodsList()
        .equals(other.getMicroservicePodsList())) return false;
    if (!getPostgresClusterPodsList()
        .equals(other.getPostgresClusterPodsList())) return false;
    if (!getKafkaClusterPodsList()
        .equals(other.getKafkaClusterPodsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMicroservicePodsCount() > 0) {
      hash = (37 * hash) + MICROSERVICE_PODS_FIELD_NUMBER;
      hash = (53 * hash) + getMicroservicePodsList().hashCode();
    }
    if (getPostgresClusterPodsCount() > 0) {
      hash = (37 * hash) + POSTGRES_CLUSTER_PODS_FIELD_NUMBER;
      hash = (53 * hash) + getPostgresClusterPodsList().hashCode();
    }
    if (getKafkaClusterPodsCount() > 0) {
      hash = (37 * hash) + KAFKA_CLUSTER_PODS_FIELD_NUMBER;
      hash = (53 * hash) + getKafkaClusterPodsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * workload pods
   * </pre>
   *
   * Protobuf type {@code leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods)
      com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPodsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leftbin.commons.proto.v1.kubernetes.resource.PodProto.internal_static_leftbin_commons_proto_v1_kubernetes_resource_WorkloadPods_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leftbin.commons.proto.v1.kubernetes.resource.PodProto.internal_static_leftbin_commons_proto_v1_kubernetes_resource_WorkloadPods_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods.class, com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods.Builder.class);
    }

    // Construct using com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (microservicePodsBuilder_ == null) {
        microservicePods_ = java.util.Collections.emptyList();
      } else {
        microservicePods_ = null;
        microservicePodsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (postgresClusterPodsBuilder_ == null) {
        postgresClusterPods_ = java.util.Collections.emptyList();
      } else {
        postgresClusterPods_ = null;
        postgresClusterPodsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (kafkaClusterPodsBuilder_ == null) {
        kafkaClusterPods_ = java.util.Collections.emptyList();
      } else {
        kafkaClusterPods_ = null;
        kafkaClusterPodsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.leftbin.commons.proto.v1.kubernetes.resource.PodProto.internal_static_leftbin_commons_proto_v1_kubernetes_resource_WorkloadPods_descriptor;
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods getDefaultInstanceForType() {
      return com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods.getDefaultInstance();
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods build() {
      com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods buildPartial() {
      com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods result = new com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods(this);
      int from_bitField0_ = bitField0_;
      if (microservicePodsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          microservicePods_ = java.util.Collections.unmodifiableList(microservicePods_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.microservicePods_ = microservicePods_;
      } else {
        result.microservicePods_ = microservicePodsBuilder_.build();
      }
      if (postgresClusterPodsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          postgresClusterPods_ = java.util.Collections.unmodifiableList(postgresClusterPods_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.postgresClusterPods_ = postgresClusterPods_;
      } else {
        result.postgresClusterPods_ = postgresClusterPodsBuilder_.build();
      }
      if (kafkaClusterPodsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          kafkaClusterPods_ = java.util.Collections.unmodifiableList(kafkaClusterPods_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.kafkaClusterPods_ = kafkaClusterPods_;
      } else {
        result.kafkaClusterPods_ = kafkaClusterPodsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods) {
        return mergeFrom((com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods other) {
      if (other == com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods.getDefaultInstance()) return this;
      if (microservicePodsBuilder_ == null) {
        if (!other.microservicePods_.isEmpty()) {
          if (microservicePods_.isEmpty()) {
            microservicePods_ = other.microservicePods_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMicroservicePodsIsMutable();
            microservicePods_.addAll(other.microservicePods_);
          }
          onChanged();
        }
      } else {
        if (!other.microservicePods_.isEmpty()) {
          if (microservicePodsBuilder_.isEmpty()) {
            microservicePodsBuilder_.dispose();
            microservicePodsBuilder_ = null;
            microservicePods_ = other.microservicePods_;
            bitField0_ = (bitField0_ & ~0x00000001);
            microservicePodsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMicroservicePodsFieldBuilder() : null;
          } else {
            microservicePodsBuilder_.addAllMessages(other.microservicePods_);
          }
        }
      }
      if (postgresClusterPodsBuilder_ == null) {
        if (!other.postgresClusterPods_.isEmpty()) {
          if (postgresClusterPods_.isEmpty()) {
            postgresClusterPods_ = other.postgresClusterPods_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePostgresClusterPodsIsMutable();
            postgresClusterPods_.addAll(other.postgresClusterPods_);
          }
          onChanged();
        }
      } else {
        if (!other.postgresClusterPods_.isEmpty()) {
          if (postgresClusterPodsBuilder_.isEmpty()) {
            postgresClusterPodsBuilder_.dispose();
            postgresClusterPodsBuilder_ = null;
            postgresClusterPods_ = other.postgresClusterPods_;
            bitField0_ = (bitField0_ & ~0x00000002);
            postgresClusterPodsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPostgresClusterPodsFieldBuilder() : null;
          } else {
            postgresClusterPodsBuilder_.addAllMessages(other.postgresClusterPods_);
          }
        }
      }
      if (kafkaClusterPodsBuilder_ == null) {
        if (!other.kafkaClusterPods_.isEmpty()) {
          if (kafkaClusterPods_.isEmpty()) {
            kafkaClusterPods_ = other.kafkaClusterPods_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureKafkaClusterPodsIsMutable();
            kafkaClusterPods_.addAll(other.kafkaClusterPods_);
          }
          onChanged();
        }
      } else {
        if (!other.kafkaClusterPods_.isEmpty()) {
          if (kafkaClusterPodsBuilder_.isEmpty()) {
            kafkaClusterPodsBuilder_.dispose();
            kafkaClusterPodsBuilder_ = null;
            kafkaClusterPods_ = other.kafkaClusterPods_;
            bitField0_ = (bitField0_ & ~0x00000004);
            kafkaClusterPodsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKafkaClusterPodsFieldBuilder() : null;
          } else {
            kafkaClusterPodsBuilder_.addAllMessages(other.kafkaClusterPods_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.leftbin.commons.proto.v1.kubernetes.resource.Pod m =
                  input.readMessage(
                      com.leftbin.commons.proto.v1.kubernetes.resource.Pod.parser(),
                      extensionRegistry);
              if (microservicePodsBuilder_ == null) {
                ensureMicroservicePodsIsMutable();
                microservicePods_.add(m);
              } else {
                microservicePodsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              com.leftbin.commons.proto.v1.kubernetes.resource.Pod m =
                  input.readMessage(
                      com.leftbin.commons.proto.v1.kubernetes.resource.Pod.parser(),
                      extensionRegistry);
              if (postgresClusterPodsBuilder_ == null) {
                ensurePostgresClusterPodsIsMutable();
                postgresClusterPods_.add(m);
              } else {
                postgresClusterPodsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.leftbin.commons.proto.v1.kubernetes.resource.Pod m =
                  input.readMessage(
                      com.leftbin.commons.proto.v1.kubernetes.resource.Pod.parser(),
                      extensionRegistry);
              if (kafkaClusterPodsBuilder_ == null) {
                ensureKafkaClusterPodsIsMutable();
                kafkaClusterPods_.add(m);
              } else {
                kafkaClusterPodsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> microservicePods_ =
      java.util.Collections.emptyList();
    private void ensureMicroservicePodsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        microservicePods_ = new java.util.ArrayList<com.leftbin.commons.proto.v1.kubernetes.resource.Pod>(microservicePods_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> microservicePodsBuilder_;

    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> getMicroservicePodsList() {
      if (microservicePodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(microservicePods_);
      } else {
        return microservicePodsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public int getMicroservicePodsCount() {
      if (microservicePodsBuilder_ == null) {
        return microservicePods_.size();
      } else {
        return microservicePodsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod getMicroservicePods(int index) {
      if (microservicePodsBuilder_ == null) {
        return microservicePods_.get(index);
      } else {
        return microservicePodsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder setMicroservicePods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (microservicePodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMicroservicePodsIsMutable();
        microservicePods_.set(index, value);
        onChanged();
      } else {
        microservicePodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder setMicroservicePods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (microservicePodsBuilder_ == null) {
        ensureMicroservicePodsIsMutable();
        microservicePods_.set(index, builderForValue.build());
        onChanged();
      } else {
        microservicePodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder addMicroservicePods(com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (microservicePodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMicroservicePodsIsMutable();
        microservicePods_.add(value);
        onChanged();
      } else {
        microservicePodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder addMicroservicePods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (microservicePodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMicroservicePodsIsMutable();
        microservicePods_.add(index, value);
        onChanged();
      } else {
        microservicePodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder addMicroservicePods(
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (microservicePodsBuilder_ == null) {
        ensureMicroservicePodsIsMutable();
        microservicePods_.add(builderForValue.build());
        onChanged();
      } else {
        microservicePodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder addMicroservicePods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (microservicePodsBuilder_ == null) {
        ensureMicroservicePodsIsMutable();
        microservicePods_.add(index, builderForValue.build());
        onChanged();
      } else {
        microservicePodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder addAllMicroservicePods(
        java.lang.Iterable<? extends com.leftbin.commons.proto.v1.kubernetes.resource.Pod> values) {
      if (microservicePodsBuilder_ == null) {
        ensureMicroservicePodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, microservicePods_);
        onChanged();
      } else {
        microservicePodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder clearMicroservicePods() {
      if (microservicePodsBuilder_ == null) {
        microservicePods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        microservicePodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public Builder removeMicroservicePods(int index) {
      if (microservicePodsBuilder_ == null) {
        ensureMicroservicePodsIsMutable();
        microservicePods_.remove(index);
        onChanged();
      } else {
        microservicePodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder getMicroservicePodsBuilder(
        int index) {
      return getMicroservicePodsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder getMicroservicePodsOrBuilder(
        int index) {
      if (microservicePodsBuilder_ == null) {
        return microservicePods_.get(index);  } else {
        return microservicePodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public java.util.List<? extends com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
         getMicroservicePodsOrBuilderList() {
      if (microservicePodsBuilder_ != null) {
        return microservicePodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(microservicePods_);
      }
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder addMicroservicePodsBuilder() {
      return getMicroservicePodsFieldBuilder().addBuilder(
          com.leftbin.commons.proto.v1.kubernetes.resource.Pod.getDefaultInstance());
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder addMicroservicePodsBuilder(
        int index) {
      return getMicroservicePodsFieldBuilder().addBuilder(
          index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.getDefaultInstance());
    }
    /**
     * <pre>
     *all pods with workload=microservice in a hosting environment are included.
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod microservice_pods = 1 [json_name = "microservicePods"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder> 
         getMicroservicePodsBuilderList() {
      return getMicroservicePodsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
        getMicroservicePodsFieldBuilder() {
      if (microservicePodsBuilder_ == null) {
        microservicePodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder>(
                microservicePods_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        microservicePods_ = null;
      }
      return microservicePodsBuilder_;
    }

    private java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> postgresClusterPods_ =
      java.util.Collections.emptyList();
    private void ensurePostgresClusterPodsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        postgresClusterPods_ = new java.util.ArrayList<com.leftbin.commons.proto.v1.kubernetes.resource.Pod>(postgresClusterPods_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> postgresClusterPodsBuilder_;

    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> getPostgresClusterPodsList() {
      if (postgresClusterPodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(postgresClusterPods_);
      } else {
        return postgresClusterPodsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public int getPostgresClusterPodsCount() {
      if (postgresClusterPodsBuilder_ == null) {
        return postgresClusterPods_.size();
      } else {
        return postgresClusterPodsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod getPostgresClusterPods(int index) {
      if (postgresClusterPodsBuilder_ == null) {
        return postgresClusterPods_.get(index);
      } else {
        return postgresClusterPodsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder setPostgresClusterPods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (postgresClusterPodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostgresClusterPodsIsMutable();
        postgresClusterPods_.set(index, value);
        onChanged();
      } else {
        postgresClusterPodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder setPostgresClusterPods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (postgresClusterPodsBuilder_ == null) {
        ensurePostgresClusterPodsIsMutable();
        postgresClusterPods_.set(index, builderForValue.build());
        onChanged();
      } else {
        postgresClusterPodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder addPostgresClusterPods(com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (postgresClusterPodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostgresClusterPodsIsMutable();
        postgresClusterPods_.add(value);
        onChanged();
      } else {
        postgresClusterPodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder addPostgresClusterPods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (postgresClusterPodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostgresClusterPodsIsMutable();
        postgresClusterPods_.add(index, value);
        onChanged();
      } else {
        postgresClusterPodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder addPostgresClusterPods(
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (postgresClusterPodsBuilder_ == null) {
        ensurePostgresClusterPodsIsMutable();
        postgresClusterPods_.add(builderForValue.build());
        onChanged();
      } else {
        postgresClusterPodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder addPostgresClusterPods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (postgresClusterPodsBuilder_ == null) {
        ensurePostgresClusterPodsIsMutable();
        postgresClusterPods_.add(index, builderForValue.build());
        onChanged();
      } else {
        postgresClusterPodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder addAllPostgresClusterPods(
        java.lang.Iterable<? extends com.leftbin.commons.proto.v1.kubernetes.resource.Pod> values) {
      if (postgresClusterPodsBuilder_ == null) {
        ensurePostgresClusterPodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, postgresClusterPods_);
        onChanged();
      } else {
        postgresClusterPodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder clearPostgresClusterPods() {
      if (postgresClusterPodsBuilder_ == null) {
        postgresClusterPods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        postgresClusterPodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public Builder removePostgresClusterPods(int index) {
      if (postgresClusterPodsBuilder_ == null) {
        ensurePostgresClusterPodsIsMutable();
        postgresClusterPods_.remove(index);
        onChanged();
      } else {
        postgresClusterPodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder getPostgresClusterPodsBuilder(
        int index) {
      return getPostgresClusterPodsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder getPostgresClusterPodsOrBuilder(
        int index) {
      if (postgresClusterPodsBuilder_ == null) {
        return postgresClusterPods_.get(index);  } else {
        return postgresClusterPodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public java.util.List<? extends com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
         getPostgresClusterPodsOrBuilderList() {
      if (postgresClusterPodsBuilder_ != null) {
        return postgresClusterPodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(postgresClusterPods_);
      }
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder addPostgresClusterPodsBuilder() {
      return getPostgresClusterPodsFieldBuilder().addBuilder(
          com.leftbin.commons.proto.v1.kubernetes.resource.Pod.getDefaultInstance());
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder addPostgresClusterPodsBuilder(
        int index) {
      return getPostgresClusterPodsFieldBuilder().addBuilder(
          index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.getDefaultInstance());
    }
    /**
     * <pre>
     *postgres cluster pods include all ancillary pods associated with the postgres cluster including entity-operator etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod postgres_cluster_pods = 2 [json_name = "postgresClusterPods"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder> 
         getPostgresClusterPodsBuilderList() {
      return getPostgresClusterPodsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
        getPostgresClusterPodsFieldBuilder() {
      if (postgresClusterPodsBuilder_ == null) {
        postgresClusterPodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder>(
                postgresClusterPods_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        postgresClusterPods_ = null;
      }
      return postgresClusterPodsBuilder_;
    }

    private java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> kafkaClusterPods_ =
      java.util.Collections.emptyList();
    private void ensureKafkaClusterPodsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        kafkaClusterPods_ = new java.util.ArrayList<com.leftbin.commons.proto.v1.kubernetes.resource.Pod>(kafkaClusterPods_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> kafkaClusterPodsBuilder_;

    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod> getKafkaClusterPodsList() {
      if (kafkaClusterPodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(kafkaClusterPods_);
      } else {
        return kafkaClusterPodsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public int getKafkaClusterPodsCount() {
      if (kafkaClusterPodsBuilder_ == null) {
        return kafkaClusterPods_.size();
      } else {
        return kafkaClusterPodsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod getKafkaClusterPods(int index) {
      if (kafkaClusterPodsBuilder_ == null) {
        return kafkaClusterPods_.get(index);
      } else {
        return kafkaClusterPodsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder setKafkaClusterPods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (kafkaClusterPodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKafkaClusterPodsIsMutable();
        kafkaClusterPods_.set(index, value);
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder setKafkaClusterPods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (kafkaClusterPodsBuilder_ == null) {
        ensureKafkaClusterPodsIsMutable();
        kafkaClusterPods_.set(index, builderForValue.build());
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder addKafkaClusterPods(com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (kafkaClusterPodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKafkaClusterPodsIsMutable();
        kafkaClusterPods_.add(value);
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder addKafkaClusterPods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod value) {
      if (kafkaClusterPodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKafkaClusterPodsIsMutable();
        kafkaClusterPods_.add(index, value);
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder addKafkaClusterPods(
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (kafkaClusterPodsBuilder_ == null) {
        ensureKafkaClusterPodsIsMutable();
        kafkaClusterPods_.add(builderForValue.build());
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder addKafkaClusterPods(
        int index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder builderForValue) {
      if (kafkaClusterPodsBuilder_ == null) {
        ensureKafkaClusterPodsIsMutable();
        kafkaClusterPods_.add(index, builderForValue.build());
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder addAllKafkaClusterPods(
        java.lang.Iterable<? extends com.leftbin.commons.proto.v1.kubernetes.resource.Pod> values) {
      if (kafkaClusterPodsBuilder_ == null) {
        ensureKafkaClusterPodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, kafkaClusterPods_);
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder clearKafkaClusterPods() {
      if (kafkaClusterPodsBuilder_ == null) {
        kafkaClusterPods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public Builder removeKafkaClusterPods(int index) {
      if (kafkaClusterPodsBuilder_ == null) {
        ensureKafkaClusterPodsIsMutable();
        kafkaClusterPods_.remove(index);
        onChanged();
      } else {
        kafkaClusterPodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder getKafkaClusterPodsBuilder(
        int index) {
      return getKafkaClusterPodsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder getKafkaClusterPodsOrBuilder(
        int index) {
      if (kafkaClusterPodsBuilder_ == null) {
        return kafkaClusterPods_.get(index);  } else {
        return kafkaClusterPodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public java.util.List<? extends com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
         getKafkaClusterPodsOrBuilderList() {
      if (kafkaClusterPodsBuilder_ != null) {
        return kafkaClusterPodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(kafkaClusterPods_);
      }
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder addKafkaClusterPodsBuilder() {
      return getKafkaClusterPodsFieldBuilder().addBuilder(
          com.leftbin.commons.proto.v1.kubernetes.resource.Pod.getDefaultInstance());
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder addKafkaClusterPodsBuilder(
        int index) {
      return getKafkaClusterPodsFieldBuilder().addBuilder(
          index, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.getDefaultInstance());
    }
    /**
     * <pre>
     *kafka cluster pods include all ancillary pods associated with the kafka cluster including schema-registry, kowl etc
     * </pre>
     *
     * <code>repeated .leftbin.commons.proto.v1.kubernetes.resource.Pod kafka_cluster_pods = 3 [json_name = "kafkaClusterPods"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder> 
         getKafkaClusterPodsBuilderList() {
      return getKafkaClusterPodsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder> 
        getKafkaClusterPodsFieldBuilder() {
      if (kafkaClusterPodsBuilder_ == null) {
        kafkaClusterPodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.leftbin.commons.proto.v1.kubernetes.resource.Pod, com.leftbin.commons.proto.v1.kubernetes.resource.Pod.Builder, com.leftbin.commons.proto.v1.kubernetes.resource.PodOrBuilder>(
                kafkaClusterPods_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        kafkaClusterPods_ = null;
      }
      return kafkaClusterPodsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods)
  }

  // @@protoc_insertion_point(class_scope:leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods)
  private static final com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods();
  }

  public static com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkloadPods>
      PARSER = new com.google.protobuf.AbstractParser<WorkloadPods>() {
    @java.lang.Override
    public WorkloadPods parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WorkloadPods> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkloadPods> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.leftbin.commons.proto.v1.kubernetes.resource.WorkloadPods getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

