// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leftbin/commons/proto/v1/kafka/model.proto

package com.leftbin.commons.proto.v1.kafka;

/**
 * <pre>
 * this is used to get meta information of kafka streams pod
 * </pre>
 *
 * Protobuf type {@code leftbin.commons.proto.v1.kafka.StreamsMeta}
 */
public final class StreamsMeta extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:leftbin.commons.proto.v1.kafka.StreamsMeta)
    StreamsMetaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamsMeta.newBuilder() to construct.
  private StreamsMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamsMeta() {
    instanceMeta_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamsMeta();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.leftbin.commons.proto.v1.kafka.ModelProto.internal_static_leftbin_commons_proto_v1_kafka_StreamsMeta_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.leftbin.commons.proto.v1.kafka.ModelProto.internal_static_leftbin_commons_proto_v1_kafka_StreamsMeta_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.leftbin.commons.proto.v1.kafka.StreamsMeta.class, com.leftbin.commons.proto.v1.kafka.StreamsMeta.Builder.class);
  }

  public static final int INSTANCE_META_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.leftbin.commons.proto.v1.kafka.InstanceMeta> instanceMeta_;
  /**
   * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
   */
  @java.lang.Override
  public java.util.List<com.leftbin.commons.proto.v1.kafka.InstanceMeta> getInstanceMetaList() {
    return instanceMeta_;
  }
  /**
   * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.leftbin.commons.proto.v1.kafka.InstanceMetaOrBuilder> 
      getInstanceMetaOrBuilderList() {
    return instanceMeta_;
  }
  /**
   * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
   */
  @java.lang.Override
  public int getInstanceMetaCount() {
    return instanceMeta_.size();
  }
  /**
   * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.kafka.InstanceMeta getInstanceMeta(int index) {
    return instanceMeta_.get(index);
  }
  /**
   * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
   */
  @java.lang.Override
  public com.leftbin.commons.proto.v1.kafka.InstanceMetaOrBuilder getInstanceMetaOrBuilder(
      int index) {
    return instanceMeta_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < instanceMeta_.size(); i++) {
      output.writeMessage(1, instanceMeta_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < instanceMeta_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, instanceMeta_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.leftbin.commons.proto.v1.kafka.StreamsMeta)) {
      return super.equals(obj);
    }
    com.leftbin.commons.proto.v1.kafka.StreamsMeta other = (com.leftbin.commons.proto.v1.kafka.StreamsMeta) obj;

    if (!getInstanceMetaList()
        .equals(other.getInstanceMetaList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInstanceMetaCount() > 0) {
      hash = (37 * hash) + INSTANCE_META_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceMetaList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.leftbin.commons.proto.v1.kafka.StreamsMeta prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * this is used to get meta information of kafka streams pod
   * </pre>
   *
   * Protobuf type {@code leftbin.commons.proto.v1.kafka.StreamsMeta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:leftbin.commons.proto.v1.kafka.StreamsMeta)
      com.leftbin.commons.proto.v1.kafka.StreamsMetaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leftbin.commons.proto.v1.kafka.ModelProto.internal_static_leftbin_commons_proto_v1_kafka_StreamsMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leftbin.commons.proto.v1.kafka.ModelProto.internal_static_leftbin_commons_proto_v1_kafka_StreamsMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leftbin.commons.proto.v1.kafka.StreamsMeta.class, com.leftbin.commons.proto.v1.kafka.StreamsMeta.Builder.class);
    }

    // Construct using com.leftbin.commons.proto.v1.kafka.StreamsMeta.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (instanceMetaBuilder_ == null) {
        instanceMeta_ = java.util.Collections.emptyList();
      } else {
        instanceMeta_ = null;
        instanceMetaBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.leftbin.commons.proto.v1.kafka.ModelProto.internal_static_leftbin_commons_proto_v1_kafka_StreamsMeta_descriptor;
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.kafka.StreamsMeta getDefaultInstanceForType() {
      return com.leftbin.commons.proto.v1.kafka.StreamsMeta.getDefaultInstance();
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.kafka.StreamsMeta build() {
      com.leftbin.commons.proto.v1.kafka.StreamsMeta result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.leftbin.commons.proto.v1.kafka.StreamsMeta buildPartial() {
      com.leftbin.commons.proto.v1.kafka.StreamsMeta result = new com.leftbin.commons.proto.v1.kafka.StreamsMeta(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.leftbin.commons.proto.v1.kafka.StreamsMeta result) {
      if (instanceMetaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          instanceMeta_ = java.util.Collections.unmodifiableList(instanceMeta_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.instanceMeta_ = instanceMeta_;
      } else {
        result.instanceMeta_ = instanceMetaBuilder_.build();
      }
    }

    private void buildPartial0(com.leftbin.commons.proto.v1.kafka.StreamsMeta result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.leftbin.commons.proto.v1.kafka.StreamsMeta) {
        return mergeFrom((com.leftbin.commons.proto.v1.kafka.StreamsMeta)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.leftbin.commons.proto.v1.kafka.StreamsMeta other) {
      if (other == com.leftbin.commons.proto.v1.kafka.StreamsMeta.getDefaultInstance()) return this;
      if (instanceMetaBuilder_ == null) {
        if (!other.instanceMeta_.isEmpty()) {
          if (instanceMeta_.isEmpty()) {
            instanceMeta_ = other.instanceMeta_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInstanceMetaIsMutable();
            instanceMeta_.addAll(other.instanceMeta_);
          }
          onChanged();
        }
      } else {
        if (!other.instanceMeta_.isEmpty()) {
          if (instanceMetaBuilder_.isEmpty()) {
            instanceMetaBuilder_.dispose();
            instanceMetaBuilder_ = null;
            instanceMeta_ = other.instanceMeta_;
            bitField0_ = (bitField0_ & ~0x00000001);
            instanceMetaBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInstanceMetaFieldBuilder() : null;
          } else {
            instanceMetaBuilder_.addAllMessages(other.instanceMeta_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.leftbin.commons.proto.v1.kafka.InstanceMeta m =
                  input.readMessage(
                      com.leftbin.commons.proto.v1.kafka.InstanceMeta.parser(),
                      extensionRegistry);
              if (instanceMetaBuilder_ == null) {
                ensureInstanceMetaIsMutable();
                instanceMeta_.add(m);
              } else {
                instanceMetaBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.leftbin.commons.proto.v1.kafka.InstanceMeta> instanceMeta_ =
      java.util.Collections.emptyList();
    private void ensureInstanceMetaIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        instanceMeta_ = new java.util.ArrayList<com.leftbin.commons.proto.v1.kafka.InstanceMeta>(instanceMeta_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.kafka.InstanceMeta, com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder, com.leftbin.commons.proto.v1.kafka.InstanceMetaOrBuilder> instanceMetaBuilder_;

    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.kafka.InstanceMeta> getInstanceMetaList() {
      if (instanceMetaBuilder_ == null) {
        return java.util.Collections.unmodifiableList(instanceMeta_);
      } else {
        return instanceMetaBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public int getInstanceMetaCount() {
      if (instanceMetaBuilder_ == null) {
        return instanceMeta_.size();
      } else {
        return instanceMetaBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public com.leftbin.commons.proto.v1.kafka.InstanceMeta getInstanceMeta(int index) {
      if (instanceMetaBuilder_ == null) {
        return instanceMeta_.get(index);
      } else {
        return instanceMetaBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder setInstanceMeta(
        int index, com.leftbin.commons.proto.v1.kafka.InstanceMeta value) {
      if (instanceMetaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstanceMetaIsMutable();
        instanceMeta_.set(index, value);
        onChanged();
      } else {
        instanceMetaBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder setInstanceMeta(
        int index, com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder builderForValue) {
      if (instanceMetaBuilder_ == null) {
        ensureInstanceMetaIsMutable();
        instanceMeta_.set(index, builderForValue.build());
        onChanged();
      } else {
        instanceMetaBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder addInstanceMeta(com.leftbin.commons.proto.v1.kafka.InstanceMeta value) {
      if (instanceMetaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstanceMetaIsMutable();
        instanceMeta_.add(value);
        onChanged();
      } else {
        instanceMetaBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder addInstanceMeta(
        int index, com.leftbin.commons.proto.v1.kafka.InstanceMeta value) {
      if (instanceMetaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstanceMetaIsMutable();
        instanceMeta_.add(index, value);
        onChanged();
      } else {
        instanceMetaBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder addInstanceMeta(
        com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder builderForValue) {
      if (instanceMetaBuilder_ == null) {
        ensureInstanceMetaIsMutable();
        instanceMeta_.add(builderForValue.build());
        onChanged();
      } else {
        instanceMetaBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder addInstanceMeta(
        int index, com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder builderForValue) {
      if (instanceMetaBuilder_ == null) {
        ensureInstanceMetaIsMutable();
        instanceMeta_.add(index, builderForValue.build());
        onChanged();
      } else {
        instanceMetaBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder addAllInstanceMeta(
        java.lang.Iterable<? extends com.leftbin.commons.proto.v1.kafka.InstanceMeta> values) {
      if (instanceMetaBuilder_ == null) {
        ensureInstanceMetaIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instanceMeta_);
        onChanged();
      } else {
        instanceMetaBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder clearInstanceMeta() {
      if (instanceMetaBuilder_ == null) {
        instanceMeta_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        instanceMetaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public Builder removeInstanceMeta(int index) {
      if (instanceMetaBuilder_ == null) {
        ensureInstanceMetaIsMutable();
        instanceMeta_.remove(index);
        onChanged();
      } else {
        instanceMetaBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder getInstanceMetaBuilder(
        int index) {
      return getInstanceMetaFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public com.leftbin.commons.proto.v1.kafka.InstanceMetaOrBuilder getInstanceMetaOrBuilder(
        int index) {
      if (instanceMetaBuilder_ == null) {
        return instanceMeta_.get(index);  } else {
        return instanceMetaBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public java.util.List<? extends com.leftbin.commons.proto.v1.kafka.InstanceMetaOrBuilder> 
         getInstanceMetaOrBuilderList() {
      if (instanceMetaBuilder_ != null) {
        return instanceMetaBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(instanceMeta_);
      }
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder addInstanceMetaBuilder() {
      return getInstanceMetaFieldBuilder().addBuilder(
          com.leftbin.commons.proto.v1.kafka.InstanceMeta.getDefaultInstance());
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder addInstanceMetaBuilder(
        int index) {
      return getInstanceMetaFieldBuilder().addBuilder(
          index, com.leftbin.commons.proto.v1.kafka.InstanceMeta.getDefaultInstance());
    }
    /**
     * <code>repeated .leftbin.commons.proto.v1.kafka.InstanceMeta instance_meta = 1 [json_name = "instanceMeta"];</code>
     */
    public java.util.List<com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder> 
         getInstanceMetaBuilderList() {
      return getInstanceMetaFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leftbin.commons.proto.v1.kafka.InstanceMeta, com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder, com.leftbin.commons.proto.v1.kafka.InstanceMetaOrBuilder> 
        getInstanceMetaFieldBuilder() {
      if (instanceMetaBuilder_ == null) {
        instanceMetaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.leftbin.commons.proto.v1.kafka.InstanceMeta, com.leftbin.commons.proto.v1.kafka.InstanceMeta.Builder, com.leftbin.commons.proto.v1.kafka.InstanceMetaOrBuilder>(
                instanceMeta_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        instanceMeta_ = null;
      }
      return instanceMetaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:leftbin.commons.proto.v1.kafka.StreamsMeta)
  }

  // @@protoc_insertion_point(class_scope:leftbin.commons.proto.v1.kafka.StreamsMeta)
  private static final com.leftbin.commons.proto.v1.kafka.StreamsMeta DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.leftbin.commons.proto.v1.kafka.StreamsMeta();
  }

  public static com.leftbin.commons.proto.v1.kafka.StreamsMeta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamsMeta>
      PARSER = new com.google.protobuf.AbstractParser<StreamsMeta>() {
    @java.lang.Override
    public StreamsMeta parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamsMeta> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamsMeta> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.leftbin.commons.proto.v1.kafka.StreamsMeta getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

